/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package IS.TA.GUI;

import IS.TA.camThread.MyThread;
import static IS.TA.camThread.VideoCap.initCamera;
import java.awt.Panel;
import javax.swing.JFrame;
import javax.swing.JRadioButton;

/**
 *
 * @author denis
 */
public class MayBeWebCam extends JFrame {

    /**
     * Creates new form MayBeWebCam
     */
    public Panel panel;
    public JRadioButton radioButton1,radioButton2;

    public MayBeWebCam()
    {
      
    }
    public MayBeWebCam(Panel panel,JRadioButton radioButton1,JRadioButton radioButton2) {
        initComponents();
        setTitle("Выбор камеры");
        setDefaultCloseOperation(MayBeWebCam.DISPOSE_ON_CLOSE);
       this.panel = panel;
       this.radioButton1 = radioButton1;
       this.radioButton2 = radioButton2;
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        webCamButton = new javax.swing.JButton();
        portButtom = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        webCamButton.setText("Использовать Web-камеру ");
        webCamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                webCamButtonActionPerformed(evt);
            }
        });

        portButtom.setText("Использовать камеру через порт");
        portButtom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portButtomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(portButtom, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(webCamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(webCamButton)
                .addGap(20, 20, 20)
                .addComponent(portButtom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void webCamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_webCamButtonActionPerformed
        // TODO add your handling code here:
         initCamera(true);
         MyThread tr = new MyThread("JThread", panel,radioButton1,radioButton2);
         tr.start();//поток, показывающий обработанные картинки
         
         this.dispose();
    }//GEN-LAST:event_webCamButtonActionPerformed

    private void portButtomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portButtomActionPerformed
        // TODO add your handling code here:
        
       initCamera(false);
       MyThread tr = new MyThread("JThread", panel,radioButton1,radioButton2);
       tr.start();//поток, показывающий обработанные картинки  
       
       this.dispose();
    }//GEN-LAST:event_portButtomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MayBeWebCam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MayBeWebCam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MayBeWebCam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MayBeWebCam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MayBeWebCam webCam = new MayBeWebCam();
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton portButtom;
    private javax.swing.JButton webCamButton;
    // End of variables declaration//GEN-END:variables

    
}
